version: '3.9'
services:
  client:
    build: .
    # container_name: proxima-crm-client
    ports:
      - 3004:3000
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.appclient.rule=Host(`app.proximaai.co`)"
      - "traefik.http.routers.appclient.tls=true"
      - "traefik.http.routers.appclient.entrypoints=websecure"
      - "traefik.http.routers.appclient.tls.certresolver=letsencrypt"
      - "traefik.http.services.appclient.loadbalancer.server.port=3000"
      # use compression
      - "traefik.http.routers.webclient.middlewares=test-compress"
      - "traefik.http.middlewares.test-compress.compress=true"
    networks:
      - traefik_proxy
      
networks:
  default:
    external:
      name: traefik_proxy