version: '3.9'
services:
  appclient:
    build: .
    ports:
      - 3004:3000
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.appclient.rule=Host(`app.proximaai.co`)"
      - "traefik.http.routers.appclient.tls=true"
      - "traefik.http.routers.appclient.entrypoints=websecure"
      - "traefik.http.routers.appclient.tls.certresolver=letsencrypt"
      - "traefik.http.services.appclient.loadbalancer.server.port=3000"
      # use compression
      - "traefik.http.routers.appclient.middlewares=test-compress"
      - "traefik.http.middlewares.test-compress.compress=true"
networks:
  default:
    external:
      name: traefik_proxy


